In [1]:
import pandas as pd
df = pd.read_excel('Insurance_Integrated_Project/insurance_claims_raw.xlsx')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   months_as_customer           1000 non-null   int64         
 1   age                          998 non-null    float64       
 2   policy_number                1000 non-null   int64         
 3   policy_bind_date             1000 non-null   datetime64[ns]
 4   policy_state                 1000 non-null   object        
 5   policy_csl                   1000 non-null   object        
 6   policy_deductable            998 non-null    float64       
 7   policy_annual_premium        997 non-null    float64       
 8   umbrella_limit               1000 non-null   int64         
 9   insured_zip                  1000 non-null   int64         
 10  insured_sex                  1000 non-null   object        
 11  insured_education_level      999 non-null   

In [3]:
df = df.drop('_c39', axis=1)

In [4]:
df = df[df['policy_number'] != 699044]

In [5]:
df.describe()

months_as_customer         age  policy_number  policy_deductable  \
count          999.000000  997.000000     999.000000         997.000000   
mean           204.150150   38.966901  546085.689690        1133.400201   
std            115.003509    9.139147  257146.228457         610.942531   
min              0.000000   19.000000  100804.000000         500.000000   
25%            116.000000   32.000000  335913.500000         500.000000   
50%            200.000000   38.000000  532330.000000        1000.000000   
75%            276.500000   44.000000  759459.500000        2000.000000   
max            479.000000   64.000000  999435.000000        2000.000000   

       policy_annual_premium  umbrella_limit    insured_zip  capital-gains  \
count             996.000000    9.990000e+02     999.000000     998.000000   
mean             1256.991155    1.102102e+06  501101.607608   25176.452906   
std               244.387564    2.298293e+06   71648.570711   27877.379027   
min               433.330000   -1.000000e+06  430104.000000       0.000000   
25%              1090.247500    0.000000e+00  448373.000000       0.000000   
50%              1257.595000    0.000000e+00  466393.000000       0.000000   
75%              1415.825000    0.000000e+00  603221.500000   51075.000000   
max              2047.590000    1.000000e+07  620962.000000  100500.000000   

        capital-loss  incident_hour_of_the_day  number_of_vehicles_involved  \
count     999.000000                999.000000                   999.000000   
mean   -26820.520521                 11.639640                     1.837838   
std     28105.366259                  6.953486                     1.018727   
min   -111100.000000                  0.000000                     1.000000   
25%    -51500.000000                  6.000000                     1.000000   
50%    -24100.000000                 12.000000                     1.000000   
75%         0.000000                 17.000000                     3.000000   
max         0.000000                 23.000000                     4.000000   

       bodily_injuries   witnesses  total_claim_amount  injury_claim  \
count       999.000000  999.000000          995.000000    998.000000   
mean          0.991992    1.485485        52748.643216   7425.861723   
std           0.820538    1.110859        26411.938125   4877.155580   
min           0.000000    0.000000          100.000000      0.000000   
25%           0.000000    1.000000        41775.000000   4285.000000   
50%           1.000000    1.000000        57900.000000   6775.000000   
75%           2.000000    2.000000        70555.000000  11295.000000   
max           2.000000    3.000000       114920.000000  21450.000000   

       property_claim  vehicle_claim    auto_year  
count      998.000000     999.000000   999.000000  
mean      7395.020040   37922.872873  2005.102102  
std       4828.122705   18894.734325     6.018807  
min          0.000000      70.000000  1995.000000  
25%       4435.000000   30275.000000  2000.000000  
50%       6745.000000   42080.000000  2005.000000  
75%      10875.000000   50845.000000  2010.000000  
max      23670.000000   79560.000000  2015.000000

In [6]:
average_age = df['age'].mean()
df['age'] =df['age'].fillna(average_age)

In [7]:
average_deductable = df['policy_deductable'].mean()
df['policy_deductable'] =df['policy_deductable'].fillna(average_deductable)

In [8]:
average_annual_premium = df['policy_annual_premium'].mean()
df['policy_annual_premium'] =df['policy_annual_premium'].fillna(average_annual_premium)

In [9]:
unique_values = df['insured_education_level'].unique()
print(unique_values)

['MD' 'PhD' 'Associate' nan 'Masters' 'High School' 'College' 'JD']


In [10]:
df['insured_education_level'] = df['insured_education_level'].fillna('College')

In [11]:
unique_values = df['insured_hobbies'].unique()
print(unique_values)

['sleeping' 'reading' 'board-games' nan 'bungie-jumping' 'base-jumping'
 'golf' 'camping' 'dancing' 'skydiving' 'movies' 'hiking' 'yachting'
 'paintball' 'chess' 'kayaking' 'basketball' 'video-games' 'polo'
 'cross-fit' 'exercise']


In [12]:
df['insured_hobbies'] = df['insured_hobbies'].fillna('unknown')

In [13]:
average_capital = df['capital-gains'].mean()
df['capital-gains'] =df['capital-gains'].fillna(average_capital)

In [14]:
df['authorities_contacted'] = df['authorities_contacted'].fillna('unknown')

In [15]:
df['incident_state'] = df['incident_state'].fillna('unknown')

In [16]:
average_amount = df['total_claim_amount'].mean()
df['total_claim_amount'] =df['total_claim_amount'].fillna(average_amount)

In [17]:
average_injury_claim = df['injury_claim'].mean()
df['injury_claim'] =df['injury_claim'].fillna(average_injury_claim)

In [18]:
average_property_claim = df['property_claim'].mean()
df['property_claim'] =df['property_claim'].fillna(average_property_claim)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 999 entries, 0 to 999
Data columns (total 39 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   months_as_customer           999 non-null    int64         
 1   age                          999 non-null    float64       
 2   policy_number                999 non-null    int64         
 3   policy_bind_date             999 non-null    datetime64[ns]
 4   policy_state                 999 non-null    object        
 5   policy_csl                   999 non-null    object        
 6   policy_deductable            999 non-null    float64       
 7   policy_annual_premium        999 non-null    float64       
 8   umbrella_limit               999 non-null    int64         
 9   insured_zip                  999 non-null    int64         
 10  insured_sex                  999 non-null    object        
 11  insured_education_level      999 non-null    

In [20]:
bin_edges = [0, 30, 55, 100]  # Define the bin edges
bin_labels = ['Young Adult', 'Middle Aged', 'Elderly']
df['ages_category'] = pd.cut(df['age'], bins=bin_edges, labels=bin_labels)

In [21]:
bin_edges_customer = [0, 25, 150, 500]  # Define the bin edges
bin_labels_customer = ['New Client', 'Established Client', 'Long-Term Client']  # Corresponding labels for each bin

# Create a new column based on the bin labels
df['customer_category'] = pd.cut(df['months_as_customer'], bins=bin_edges_customer, labels=bin_labels_customer)

In [22]:
df['total_premiums_paid'] = (df['policy_annual_premium']/12) * df['months_as_customer']

In [23]:
df['net_value_of_customer'] = df['total_premiums_paid'] - df['total_claim_amount']

In [24]:
df.to_csv('Cleaned_Insurance_Features.csv', index=False)

In [26]:
df = df.drop(columns=['policy_number','policy_bind_date','policy_state', 'policy_csl','insured_zip','umbrella_limit','insured_relationship','capital-gains','capital-loss','incident_date','collision_type','authorities_contacted','incident_state','incident_city','incident_location','property_damage','bodily_injuries','injury_claim','property_claim','total_claim_amount'])

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 999 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype   
---  ------                       --------------  -----   
 0   months_as_customer           999 non-null    int64   
 1   age                          999 non-null    float64 
 2   policy_deductable            999 non-null    float64 
 3   policy_annual_premium        999 non-null    float64 
 4   insured_sex                  999 non-null    object  
 5   insured_education_level      999 non-null    object  
 6   insured_occupation           999 non-null    object  
 7   insured_hobbies              999 non-null    object  
 8   incident_type                999 non-null    object  
 9   incident_severity            999 non-null    object  
 10  incident_hour_of_the_day     999 non-null    int64   
 11  number_of_vehicles_involved  999 non-null    int64   
 12  witnesses                    999 non-null    int64   
 13  polic

In [28]:
import pandas as pd
df['insured_sex'] = df['insured_sex'].replace({'Female':1,'Male':2})

In [29]:
df['insured_education_level'] = df['insured_education_level'].replace({'Associate':1,'College':2, 'High School':3, 'JD' :4, 'Masters' :5, 'MD' :5, 'PHD' :6})

In [53]:
df['insured_occupation'] = df['insured_occupation'].replace({'adm-clerical':1,'armed-forces':2, 'craft-repair':3, 'exec-managerial' :4, 'farming-fishing' :5, 'handlers-cleaners' :6, 'machine-op-inspct' :7, 'other-service':8, 'priv-house-serv':9, 'prof-specialty':10, 'protective-serv':11, 'sales':12, 'tech-support':13, 'transport-moving':14})

In [31]:
df['incident_type'] = df['incident_type'].replace({'Multi-vehicle Collision':1,'Parked Car':2, 'Single Vehicle Collision':3, 'Vehicle Theft':4})

In [33]:
df['incident_severity'] = df['incident_severity'].replace({'Major Damage':1,'Minor Damage':2, 'Total Loss':3, 'Trivial Damage':4})

In [34]:
df['police_report_available'] = df['police_report_available'].replace({'Yes':1,'No':2})

In [35]:
df['fraud_reported'] = df['fraud_reported'].replace({'Yes':1,'No':2})

In [36]:
df['ages_category'] = df['ages_category'].replace({'Elderly':1,'Middle Aged':2, 'Young Adult':3})

In [37]:
df['customer_category'] = df['customer_category'].replace({'Established Client':1,'Long-Term Client':2, 'New Client':3})

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 999 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype   
---  ------                       --------------  -----   
 0   months_as_customer           999 non-null    int64   
 1   age                          999 non-null    float64 
 2   policy_deductable            999 non-null    float64 
 3   policy_annual_premium        999 non-null    float64 
 4   insured_sex                  999 non-null    object  
 5   insured_education_level      999 non-null    object  
 6   insured_occupation           999 non-null    int64   
 7   insured_hobbies              999 non-null    object  
 8   incident_type                999 non-null    int64   
 9   incident_severity            999 non-null    int64   
 10  incident_hour_of_the_day     999 non-null    int64   
 11  number_of_vehicles_involved  999 non-null    int64   
 12  witnesses                    999 non-null    int64   
 13  polic

In [39]:
unique_sex = df['insured_sex'].unique()
print(unique_sex)

['MALE' 'FEMALE']


In [42]:
df['insured_sex'] = df['insured_sex'].replace({'FEMALE':1,'MALE':2})

In [43]:
unique_sex = df['insured_sex'].unique()
print(unique_sex)

[2 1]


In [44]:
unique_edu = df['insured_education_level'].unique()
print(unique_edu)

[5 'PhD' 1 2 3 4]


In [45]:
df['insured_education_level'] = df['insured_education_level'].replace({'Associate':1,'College':2, 'High School':3, 'JD' :4, 'Masters' :5, 'MD' :5, 'PhD' :6})

In [46]:
unique_edu = df['insured_education_level'].unique()
print(unique_edu)

[5 6 1 2 3 4]


In [47]:
unique_hob = df['insured_hobbies'].unique()
print(unique_hob)

['sleeping' 'reading' 'board-games' 'unknown' 'bungie-jumping'
 'base-jumping' 'golf' 'camping' 'dancing' 'skydiving' 'movies' 'hiking'
 'yachting' 'paintball' 'chess' 'kayaking' 'basketball' 'video-games'
 'polo' 'cross-fit' 'exercise']


In [51]:
df['insured_hobbies'] = df['insured_hobbies'].replace({'sleeping':1,'reading':2, 'board-games':3, 'unknown':4, 'bungie-jumping':5, 'base-jumping':6, 'golf':7, 'camping':8, 'dancing':9, 'skydiving':10, 'movies':11, 'hiking':12, 'yachting':13, 'paintball':14, 'chess':15, 'kayaking':16, 'basketball' :17, 'video-games':18, 'polo':19, 'cross-fit':20, 'exercise':21})

In [52]:
unique_hob = df['insured_hobbies'].unique()
print(unique_hob)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


In [54]:
unique_report = df['police_report_available'].unique()
print(unique_report)

['YES' '?' 'NO']


In [57]:
df['police_report_available'] = df['police_report_available'].replace({'YES':1,'NO':2, '?':3})

In [58]:
unique_report = df['police_report_available'].unique()
print(unique_report)

[1 3 2]


In [59]:
unique_make = df['auto_make'].unique()
print(unique_make)

['Saab' 'Mercedes' 'Dodge' 'Chevrolet' 'Accura' 'Nissan' 'Audi' 'Toyota'
 'Ford' 'Suburu' 'BMW' 'Jeep' 'Honda' 'Volkswagen']


In [63]:
df['auto_make'] = df['auto_make'].replace({'Saab':1,'Mercedes':2, 'Dodge':3, 'Chevrolet':4, 'Accura':5, 'Nissan':6, 'Audi':7, 'Toyota':8,'Ford':9, 'Suburu':10, 'BMW':11, 'Jeep':12, 'Honda':13, 'Volkswagen':14})

In [64]:
unique_make = df['auto_make'].unique()
print(unique_make)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [65]:
unique_model = df['auto_model'].unique()
print(unique_model)

['92x' 'E400' 'RAM' 'Tahoe' 'RSX' 95 'Pathfinder' 'A5' 'Camry' 'F150' 'A3'
 'Highlander' 'Neon' 'MDX' 'Maxima' 'Legacy' 'TL' 'Impreza' 'Forrestor'
 'Escape' 'Corolla' '3 Series' 'C300' 'Wrangler' 'M5' 'X5' 'Civic'
 'Passat' 'Silverado' 'CRV' 93 'Accord' 'X6' 'Malibu' 'Fusion' 'Jetta'
 'ML350' 'Ultima' 'Grand Cherokee']


In [66]:
df = df.drop('auto_model', axis=1)

In [67]:
unique_reported = df['fraud_reported'].unique()
print(unique_reported)

['Y' 'N']


In [68]:
df['fraud_reported'] = df['fraud_reported'].replace({'Y':1,'N':2})

In [69]:
unique_reported = df['fraud_reported'].unique()
print(unique_reported)

[1 2]


In [70]:
unique_agesC = df['ages_category'].unique()
print(unique_agesC)

[2, 3, 1]
Categories (3, int64): [3 < 2 < 1]


In [71]:
df['ages_category'] = df['ages_category'].cat.codes

In [72]:
unique_agesC = df['ages_category'].unique()
print(unique_agesC)

[1 0 2]


In [73]:
unique_custC = df['customer_category'].unique()
print(unique_custC)

[2, 1, 3, NaN]
Categories (3, int64): [3 < 1 < 2]


In [74]:
df['customer_category'] = df['customer_category'].cat.codes

In [75]:
unique_custC = df['customer_category'].unique()
print(unique_custC)

[ 2  1  0 -1]


In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 999 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   months_as_customer           999 non-null    int64  
 1   age                          999 non-null    float64
 2   policy_deductable            999 non-null    float64
 3   policy_annual_premium        999 non-null    float64
 4   insured_sex                  999 non-null    int64  
 5   insured_education_level      999 non-null    int64  
 6   insured_occupation           999 non-null    int64  
 7   insured_hobbies              999 non-null    int64  
 8   incident_type                999 non-null    int64  
 9   incident_severity            999 non-null    int64  
 10  incident_hour_of_the_day     999 non-null    int64  
 11  number_of_vehicles_involved  999 non-null    int64  
 12  witnesses                    999 non-null    int64  
 13  police_report_availa

In [77]:
print(df.isna().any().any())

False


In [83]:
# split data
# Split the dataset into the response, y, and features, X
y = df['fraud_reported']
X = df.drop('fraud_reported', axis=1)

In [84]:
from sklearn.model_selection import train_test_split
#Separating our models into training set and testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [85]:
# create targets and features dataset
print('Training predictor:', X_train.shape)
print('Training target:', y_train.shape)
print('Testing predictor:', X_test.shape)
print('Testing target:', y_test.shape)

Training predictor: (799, 21)
Training target: (799,)
Testing predictor: (200, 21)
Testing target: (200,)


In [86]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
# Train a Random Forest Regressor
rf = RandomForestRegressor()
rf.fit(X_train, y_train)
# Get feature importances
feature_importances = rf.feature_importances_

# Sort feature importances in descending order
indices = np.argsort(feature_importances)[::-1]

# Select the top N features
top_n = 15  # Number of top features to select
selected_features = X_train.columns[indices[:top_n]]

# Rebuild the model with selected features
X_train_selected = X_train[selected_features]
rf_selected = RandomForestRegressor()
rf_selected.fit(X_train_selected, y_train)

# Evaluate the model with selected features

X_test_selected = X_test[selected_features]
y_pred_selected = rf_selected.predict(X_test_selected)

# Evaluate model performance
# Compare rf_selected performance with rf (the original model)

In [89]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Calculate MAE
mae = mean_absolute_error(y_test, y_pred_selected)

# Calculate MSE
mse = mean_squared_error(y_test, y_pred_selected)

# Calculate RMSE
rmse = np.sqrt(mse)

# Calculate R-squared
r2 = r2_score(y_test, y_pred_selected)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R-squared:", r2)



Mean Absolute Error: 0.225
Mean Squared Error: 0.109273
Root Mean Squared Error: 0.3305646684084674
R-squared: 0.40091557017543855
